import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Foot from "@/components/Footer";

export const metadata: Metadata = {
  title: "My Posts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="grid grid-rows-[auto_1fr_auto] h-screen">
          <Header />
          <main className="text-center m-auto">{children}</main>
          <Foot />
        </div>
      </body>
    </html>
  );
}
